name: "Deploy"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  terraform:
    name: "Deploy"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Migrate
        env:
          DB_URL: postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:5432/${{ secrets.DB_NAME }}
        run: make migrate

      - name: Login Docker Hub
        run: make build/login

      - name: Build Image
        run: make build/prod

      - name: Add Tag
        run: make build/tag

      - name: Push Image
        run: make build/push
